---

- name: Install nginx
  apt: pkg=nginx state=present update_cache=no

- name: Set nginx conf
  template: src=nginx.conf dest=/etc/nginx/sites-available/gocco.conf

- name: Remove default nginx
  file: path=/etc/nginx/sites-available/default
        state=absent

- name: Enable new site
  file: src=/etc/nginx/sites-available/gocco.conf 
        dest=/etc/nginx/sites-enabled/gocco.conf
        state=link
  notify:
    - restart nginx
